# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.destroy_all
Recipe.destroy_all
RecipeItem.destroy_all
Favorite.destroy_all
CustomRecipe.destroy_all
u1 = User.create!(username: "Guest", password: "password")

r1=Recipe.create!(title: "Vegetable Fried Rice", description: "with Torgarashi Peanuts",image_file_name:"https://s3.us-east-2.amazonaws.com/greenapron/Fried+Rice.png",ingredients:"Jasmine rice, Carrots, Baby bok choy, Broccoli, Eggs, Hoisin Sauce")
r5=Recipe.create!(title: "Chicken and Orange-Kale Salad", description: "with Spicy Tahini Dressing",image_file_name:"https://s3.us-east-2.amazonaws.com/greenapron/Chicken+and+Orange-Kale+Salad.png",ingredients:"Boneless Chicken, Radishes, Kale, Avocado")
r6=Recipe.create!(title: "Orange-Glazed Meatballs", description: "with Bok Choy & Jasmine Rice",image_file_name:"https://s3.us-east-2.amazonaws.com/greenapron/Orange+Glazed+Meatballs.png",ingredients:"Ground Beef, Baby Bok Choy, Garlic, Carrots, Jasmine Rice")
r7=Recipe.create!(title: "Soy-Tahini Wonton Noodles", description: "with Bok Choy & Soft-Boiled Eggs",image_file_name:"https://s3.us-east-2.amazonaws.com/greenapron/WontonNoodles.png",ingredients:"Cage free eggs, Wonton noodles, Cabbage, Scallions")
r8=Recipe.create!(title: "Sweet Potato and Mushroom Bao", description: "with Hoisin Mayo & Cabbage Slaw",image_file_name:"https://s3.us-east-2.amazonaws.com/greenapron/Sweet+Potato.png",ingredients:"Cage free eggs, Wonton noodles, Cabbage, Scallions")
r9=Recipe.create!(title: "Miso Glazed Barramundi", description: "with Roasted Vegetables & Garlic Rice",image_file_name:"https://s3.us-east-2.amazonaws.com/greenapron/MisoBarramundi.png",ingredients:"Cage free eggs, Wonton noodles, Cabbage, Scallions")
r2=Recipe.create!(title: "General Tso's Chicken", description: "with Bok Choy and Jasmine Rice",image_file_name:"https://s3.us-east-2.amazonaws.com/greenapron/General+Tso's.png", ingredients: "Chicken breast, Bok choy, Jasmine rice, Garlic, Rice vinegar")
r3 = Recipe.create!(title: "Mushroom and Goat Cheese Quiche", description: "with Green Leaf Lettuce Salad", image_file_name:"https://s3.us-east-2.amazonaws.com/greenapron/MushroomQuiche.png", ingredients: "Garlic, Lemon, Eggs, Mushrooms, Lettuce, Pie crusts")
r4=Recipe.create!(title: "Seared Salmon", description: "with Roasted Red Onion Vinaigrette",image_file_name:"https://s3.us-east-2.amazonaws.com/greenapron/Salmon.png",ingredients:"Salmon fillet,Dried dates,Carrots,Red Onion, Cabbage")


ri1 = RecipeItem.create!(recipe_id: r1.id, item_title:"Prepare and roast the broccoli", item_description: "Remove the honey from the refrigerator to bring to room temperature. Place an oven rack in the center of the oven, then preheat to 450°F. Wash and dry the fresh produce. Cut off and discard the bottom 1/2 inch of the broccoli stem; cut the broccoli into small pieces, keeping the florets intact. Place on a sheet pan. Drizzle with olive oil and season with salt, pepper, and half the togarashi seasoning; toss to coat. Arrange in an even layer. Roast 15 to 17 minutes, or until browned and tender when pierced with a fork. Remove from the oven.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/FriedRice1.png")
ri2 = RecipeItem.create!(recipe_id: r1.id, item_title:"Cook the rice", item_description: "While the broccoli roasts, in a small pot, combine the rice, a big pinch of salt, and 1 1/2 cups of water. Heat to boiling on high. Once boiling, cover and reduce the heat to low. Cook 12 to 14 minutes, or until the water has been absorbed and the rice is tender. Turn off the heat and fluff with a fork. Cover to keep warm.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/FriedRice2.png")
ri3 = RecipeItem.create!(recipe_id: r1.id, item_title:"Prepare the remaining ingredients and make the sauce", item_description: "While the rice cooks, roughly chop the peanuts. Peel the carrots; thinly slice on an angle. Peel and finely chop the ginger. Cut off and discard the root end of the bok choy; roughly chop. Crack the eggs into a bowl; season with salt and pepper and beat until smooth. In a separate bowl, whisk together the hoisin sauce, vinegar, honey (kneading the packet before opening), and as much of the sriracha as you’d like, depending on how spicy you’d like the dish to be.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/FriedRice3.png")
ri4 = RecipeItem.create!(recipe_id: r1.id, item_title:"Make the togarashi peanuts", item_description: "In a large pan (nonstick, if you have one), heat 2 teaspoons of olive oil on medium-high until hot. Add the chopped peanuts and remaining togarashi seasoning. Cook, stirring constantly, 1 to 2 minutes, or until coated and fragrant. Transfer to a plate; immediately season with salt and pepper. Rinse and wipe out the pan.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/FriedRice4.png")
ri5 = RecipeItem.create!(recipe_id: r1.id, item_title:"Cook the vegetables and eggs", item_description: "In the same pan, heat 2 teaspoons of olive oil on medium-high until hot. Add the sliced carrots and chopped ginger; season with salt and pepper. Cook, stirring occasionally, 3 to 4 minutes, or until lightly browned and slightly softened. Add the chopped bok choy; season with salt and pepper. Cook, stirring frequently, 1 to 2 minutes, or until slightly softened. Using a spoon, move the vegetables to one side of the pan. Add 1 teaspoon of olive oil and the beaten eggs to the other side. Cook, constantly stirring the eggs, 30 seconds to 1 minute, or until cooked through. Stir the vegetables and eggs to combine. Transfer to a large bowl. Wipe out the pan.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/FriedRice5.png")
ri6 = RecipeItem.create!(recipe_id: r1.id, item_title:"Finish and serve", item_description: "In the same pan, heat 1 tablespoon of olive oil on medium-high until hot. Add the cooked rice in an even layer and cook, without stirring, 3 to 4 minutes, or until slightly crispy. Add the sauce and cook, stirring constantly, 30 seconds to 1 minute, or until combined. Transfer to the bowl of cooked vegetables and eggs. Add the roasted broccoli. Stir to thoroughly combine; season with salt and pepper to taste. Garnish the finished rice with the togarashi peanuts. Enjoy!", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/FriedRice6.png")
ri7 = RecipeItem.create!(recipe_id: r5.id, item_title:"Prepare & roast the potatoes", item_description: "Place an oven rack in the center of the oven, then preheat to 450°F. Wash and dry the fresh produce. Halve the potatoes lengthwise, then cut crosswise into 1/2-inch-thick pieces. Place on a sheet pan; drizzle with olive oil and season with salt and pepper. Toss to coat. Arrange in an even layer. Roast, flipping halfway through, 20 to 22 minutes, or until lightly browned and tender when pierced with a fork. Remove from the oven.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/ChickenKale1.png")
ri8 = RecipeItem.create!(recipe_id: r5.id, item_title:"Make the dressing & marinate the kale", item_description: "While the potatoes roast, peel and finely chop the garlic; using the flat side of your knife, smash until it resembles a paste (or use a zester). Remove and discard the stems of the kale; thinly slice the leaves. In a large bowl, whisk together the tahini, 1 tablespoon of olive oil, 1 tablespoon of water, half the vinegar, as much of the garlic paste as you’d like, and as much of the chile paste as you’d like, depending on how spicy you’d like the dish to be. Season with salt and pepper. Add the sliced kale to the bowl; season with salt and pepper. Toss to coat. Using your hands, vigorously massage the kale for 1 to 2 minutes, or until slightly softened. Set aside to marinate, stirring occasionally, for at least 10 minutes.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/ChickenKale2.png")
ri9 = RecipeItem.create!(recipe_id: r5.id, item_title:"Cook the chicken", item_description: "While the kale marinates, pat the chicken dry with paper towels; season with salt and pepper on both sides. In a medium pan, heat a drizzle of olive oil on medium-high until hot. Add the seasoned chicken and cook 5 to 7 minutes per side, or until browned and cooked through. Transfer to a cutting board.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/ChickenKale3.png")
ri10 = RecipeItem.create!(recipe_id: r5.id, item_title:"Prepare the remaining ingredients", item_description: "While the chicken cooks, cut off and discard the ends of the radishes; halve lengthwise, then thinly slice crosswise. Place in a bowl and top with a drizzle of olive oil; season with salt and pepper. Peel the orange; halve lengthwise, then thinly slice crosswise, discarding any seeds. Pit, peel, and thinly slice the avocado. Place in a bowl and top with the remaining vinegar and a drizzle of olive oil to prevent browning. Season with salt and pepper.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/ChickenKale4.png")
ri11 = RecipeItem.create!(recipe_id: r5.id, item_title:"Make the salad & serve your dish", item_description: "Thinly slice the cooked chicken crosswise. Add the sliced radishes and orange and roasted potatoes to the bowl of marinated kale; stir to combine. Season with salt and pepper to taste. Serve the salad topped with the sliced chicken and seasoned avocado. Enjoy!", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/ChickenKale5.png")
ri12 = RecipeItem.create!(recipe_id: r6.id, item_title:"Prepare the ingredients & make the sauce", item_description: "Wash and dry the fresh produce. Peel and finely chop the garlic and ginger. Peel the carrots and thinly slice on an angle. Cut off and discard the root end of the bok choy; roughly chop. Halve the orange and squeeze the juice into a medium bowl, straining out any seeds. Add the ponzu sauce and sweet chili sauce; stir to thoroughly combine.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/Meatballs1.png")
ri13 = RecipeItem.create!(recipe_id: r6.id, item_title:"Cook the rice", item_description: "In a small pot, combine the rice, a big pinch of salt, and 1 1/2 cups of water. Heat to boiling on high. Once boiling, cover and reduce the heat to low. Cook 12 to 14 minutes, or until the water has been absorbed and the rice is tender. Turn off the heat and fluff with a fork. Cover to keep warm.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/Meatballs2.png")
ri14 = RecipeItem.create!(recipe_id: r6.id, item_title:"Form the meatballs", item_description: "While the rice cooks, in a large bowl, combine the beef, breadcrumbs, and chopped garlic and ginger; season with salt and pepper. Gently mix until just combined. Using your hands, form the mixture into 10 to 12 equal-sized meatballs. Transfer to a plate.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/Meatballs3.png")
ri15 = RecipeItem.create!(recipe_id: r6.id, item_title:"Cook the meatballs & carrots", item_description: "While the rice continues to cook, in a large pan (nonstick, if you have one), heat a drizzle of olive oil on medium-high until hot. Add the meatballs and cook, turning occasionally (carefully, as the oil may splatter), 3 to 4 minutes, or until lightly browned. Add the sliced carrots; season with salt and pepper. Cook, stirring occasionally, 2 to 3 minutes, or until slightly softened.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/Meatballs4.png")
ri16 = RecipeItem.create!(recipe_id: r6.id, item_title:"Finish and serve", item_description: "Add the chopped bok choy and sauce to the pan; season with salt and pepper. Cook, stirring frequently, 3 to 4 minutes, or until the sauce is slightly thickened and the meatballs are glazed and cooked through. Turn off the heat. Serve the finished meatballs, vegetables, and sauce over the cooked rice. Enjoy!", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/Meatballs5.png")
ri17 = RecipeItem.create!(recipe_id: r7.id, item_title:"Prepare the ingredients", item_description: "Heat a medium pot of water to boiling on high. Wash and dry the fresh produce. Peel and finely chop the ginger. Cut out and discard the core of the cabbage; thinly slice the leaves. Peel the carrots; thinly slice on angle. Cut off and discard the root ends of the scallions; thinly slice, separating the white bottoms and green tops. Cut off and discard the root end of the bok choy; roughly chop. Roughly chop the peanuts.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/WontonNoodle1.png")
ri18 = RecipeItem.create!(recipe_id: r7.id, item_title:"Make the soft-boiled eggs", item_description: "Carefully add the eggs to the pot of boiling water and cook 6 to 7 minutes. Leaving the pot of water boiling, using a slotted spoon or tongs, carefully transfer the cooked eggs to a strainer; rinse under cold water for 30 seconds to 1 minute to stop the cooking process. When cool enough to handle, carefully peel.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/WontonNoodle2.png")
ri19 = RecipeItem.create!(recipe_id: r7.id, item_title:"Cook the vegetables", item_description: "While the eggs cook, in a large, high-sided pan (or pot), heat 1 tablespoon of olive oil on medium-high until hot. Add the chopped ginger and sliced cabbage, carrots, and white bottoms of the scallions. Season with salt and pepper. Cook, stirring frequently, 5 to 6 minutes, or until softened. Add the chopped bok choy and cook, stirring occasionally, 2 to 3 minutes, or until softened. Turn off the heat.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/WontonNoodle3.png")
ri20 = RecipeItem.create!(recipe_id: r7.id, item_title:"Cook the noodles", item_description: "While the vegetables cook, add the noodles to the same pot of boiling water, stirring gently to separate. Cook 2 to 4 minutes, or until tender. Drain thoroughly.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/WontonNoodle4.png")
ri21 = RecipeItem.create!(recipe_id: r7.id, item_title:"Make the sauce", item_description: "While the noodles cook, in a medium bowl, whisk together the soy glaze, tahini, sweet chili sauce, vinegar, and half the soy marinade (you will have extra soy marinade).", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/WontonNoodle5.png")
ri22 = RecipeItem.create!(recipe_id: r7.id, item_title:"Finish and serve", item_description: "Add the cooked noodles and sauce to the pan of cooked vegetables. Cook on medium-high, stirring vigorously, 1 to 2 minutes, or until coated. Turn off the heat. Season with salt and pepper to taste. Serve the finished noodles topped with the soft-boiled eggs. Garnish with the chopped peanuts and sliced green tops of the scallions. Enjoy!", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/WontonNoodle6.png")

ri23 = RecipeItem.create!(recipe_id: r8.id, item_title:"Prepare and roast the broccoli", item_description: "Remove the honey from the refrigerator to bring to room temperature. Place an oven rack in the center of the oven, then preheat to 450°F. Wash and dry the fresh produce. Cut off and discard the bottom 1/2 inch of the broccoli stem; cut the broccoli into small pieces, keeping the florets intact. Place on a sheet pan. Drizzle with olive oil and season with salt, pepper, and half the togarashi seasoning; toss to coat. Arrange in an even layer. Roast 15 to 17 minutes, or until browned and tender when pierced with a fork. Remove from the oven.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/FriedRice1.png")
ri24 = RecipeItem.create!(recipe_id: r8.id, item_title:"Cook the rice", item_description: "While the broccoli roasts, in a small pot, combine the rice, a big pinch of salt, and 1 1/2 cups of water. Heat to boiling on high. Once boiling, cover and reduce the heat to low. Cook 12 to 14 minutes, or until the water has been absorbed and the rice is tender. Turn off the heat and fluff with a fork. Cover to keep warm.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/FriedRice2.png")
ri25 = RecipeItem.create!(recipe_id: r8.id, item_title:"Prepare the remaining ingredients and make the sauce", item_description: "While the rice cooks, roughly chop the peanuts. Peel the carrots; thinly slice on an angle. Peel and finely chop the ginger. Cut off and discard the root end of the bok choy; roughly chop. Crack the eggs into a bowl; season with salt and pepper and beat until smooth. In a separate bowl, whisk together the hoisin sauce, vinegar, honey (kneading the packet before opening), and as much of the sriracha as you’d like, depending on how spicy you’d like the dish to be.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/FriedRice3.png")
ri26 = RecipeItem.create!(recipe_id: r8.id, item_title:"Make the togarashi peanuts", item_description: "In a large pan (nonstick, if you have one), heat 2 teaspoons of olive oil on medium-high until hot. Add the chopped peanuts and remaining togarashi seasoning. Cook, stirring constantly, 1 to 2 minutes, or until coated and fragrant. Transfer to a plate; immediately season with salt and pepper. Rinse and wipe out the pan.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/FriedRice4.png")
ri27 = RecipeItem.create!(recipe_id: r8.id, item_title:"Cook the vegetables and eggs", item_description: "In the same pan, heat 2 teaspoons of olive oil on medium-high until hot. Add the sliced carrots and chopped ginger; season with salt and pepper. Cook, stirring occasionally, 3 to 4 minutes, or until lightly browned and slightly softened. Add the chopped bok choy; season with salt and pepper. Cook, stirring frequently, 1 to 2 minutes, or until slightly softened. Using a spoon, move the vegetables to one side of the pan. Add 1 teaspoon of olive oil and the beaten eggs to the other side. Cook, constantly stirring the eggs, 30 seconds to 1 minute, or until cooked through. Stir the vegetables and eggs to combine. Transfer to a large bowl. Wipe out the pan.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/FriedRice5.png")
ri28 = RecipeItem.create!(recipe_id: r8.id, item_title:"Finish and serve", item_description: "In the same pan, heat 1 tablespoon of olive oil on medium-high until hot. Add the cooked rice in an even layer and cook, without stirring, 3 to 4 minutes, or until slightly crispy. Add the sauce and cook, stirring constantly, 30 seconds to 1 minute, or until combined. Transfer to the bowl of cooked vegetables and eggs. Add the roasted broccoli. Stir to thoroughly combine; season with salt and pepper to taste. Garnish the finished rice with the togarashi peanuts. Enjoy!", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/FriedRice6.png")

ri29 = RecipeItem.create!(recipe_id: r9.id, item_title:"Prepare & roast the potatoes", item_description: "Place an oven rack in the center of the oven, then preheat to 450°F. Wash and dry the fresh produce. Halve the potatoes lengthwise, then cut crosswise into 1/2-inch-thick pieces. Place on a sheet pan; drizzle with olive oil and season with salt and pepper. Toss to coat. Arrange in an even layer. Roast, flipping halfway through, 20 to 22 minutes, or until lightly browned and tender when pierced with a fork. Remove from the oven.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/ChickenKale1.png")
ri30 = RecipeItem.create!(recipe_id: r9.id, item_title:"Make the dressing & marinate the kale", item_description: "While the potatoes roast, peel and finely chop the garlic; using the flat side of your knife, smash until it resembles a paste (or use a zester). Remove and discard the stems of the kale; thinly slice the leaves. In a large bowl, whisk together the tahini, 1 tablespoon of olive oil, 1 tablespoon of water, half the vinegar, as much of the garlic paste as you’d like, and as much of the chile paste as you’d like, depending on how spicy you’d like the dish to be. Season with salt and pepper. Add the sliced kale to the bowl; season with salt and pepper. Toss to coat. Using your hands, vigorously massage the kale for 1 to 2 minutes, or until slightly softened. Set aside to marinate, stirring occasionally, for at least 10 minutes.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/ChickenKale2.png")
ri31 = RecipeItem.create!(recipe_id: r9.id, item_title:"Cook the chicken", item_description: "While the kale marinates, pat the chicken dry with paper towels; season with salt and pepper on both sides. In a medium pan, heat a drizzle of olive oil on medium-high until hot. Add the seasoned chicken and cook 5 to 7 minutes per side, or until browned and cooked through. Transfer to a cutting board.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/ChickenKale3.png")
ri32 = RecipeItem.create!(recipe_id: r9.id, item_title:"Prepare the remaining ingredients", item_description: "While the chicken cooks, cut off and discard the ends of the radishes; halve lengthwise, then thinly slice crosswise. Place in a bowl and top with a drizzle of olive oil; season with salt and pepper. Peel the orange; halve lengthwise, then thinly slice crosswise, discarding any seeds. Pit, peel, and thinly slice the avocado. Place in a bowl and top with the remaining vinegar and a drizzle of olive oil to prevent browning. Season with salt and pepper.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/ChickenKale4.png")
ri33 = RecipeItem.create!(recipe_id: r9.id, item_title:"Make the salad & serve your dish", item_description: "Thinly slice the cooked chicken crosswise. Add the sliced radishes and orange and roasted potatoes to the bowl of marinated kale; stir to combine. Season with salt and pepper to taste. Serve the salad topped with the sliced chicken and seasoned avocado. Enjoy!", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/ChickenKale5.png")

ri34 = RecipeItem.create!(recipe_id: r2.id, item_title:"Prepare the ingredients & make the sauce", item_description: "Wash and dry the fresh produce. Peel and finely chop the garlic and ginger. Peel the carrots and thinly slice on an angle. Cut off and discard the root end of the bok choy; roughly chop. Halve the orange and squeeze the juice into a medium bowl, straining out any seeds. Add the ponzu sauce and sweet chili sauce; stir to thoroughly combine.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/Meatballs1.png")
ri35 = RecipeItem.create!(recipe_id: r2.id, item_title:"Cook the rice", item_description: "In a small pot, combine the rice, a big pinch of salt, and 1 1/2 cups of water. Heat to boiling on high. Once boiling, cover and reduce the heat to low. Cook 12 to 14 minutes, or until the water has been absorbed and the rice is tender. Turn off the heat and fluff with a fork. Cover to keep warm.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/Meatballs2.png")
ri36 = RecipeItem.create!(recipe_id: r2.id, item_title:"Form the meatballs", item_description: "While the rice cooks, in a large bowl, combine the beef, breadcrumbs, and chopped garlic and ginger; season with salt and pepper. Gently mix until just combined. Using your hands, form the mixture into 10 to 12 equal-sized meatballs. Transfer to a plate.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/Meatballs3.png")
ri37 = RecipeItem.create!(recipe_id: r2.id, item_title:"Cook the meatballs & carrots", item_description: "While the rice continues to cook, in a large pan (nonstick, if you have one), heat a drizzle of olive oil on medium-high until hot. Add the meatballs and cook, turning occasionally (carefully, as the oil may splatter), 3 to 4 minutes, or until lightly browned. Add the sliced carrots; season with salt and pepper. Cook, stirring occasionally, 2 to 3 minutes, or until slightly softened.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/Meatballs4.png")
ri38 = RecipeItem.create!(recipe_id: r2.id, item_title:"Finish and serve", item_description: "Add the chopped bok choy and sauce to the pan; season with salt and pepper. Cook, stirring frequently, 3 to 4 minutes, or until the sauce is slightly thickened and the meatballs are glazed and cooked through. Turn off the heat. Serve the finished meatballs, vegetables, and sauce over the cooked rice. Enjoy!", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/Meatballs5.png")

ri39 = RecipeItem.create!(recipe_id: r3.id, item_title:"Prepare the ingredients", item_description: "Heat a medium pot of water to boiling on high. Wash and dry the fresh produce. Peel and finely chop the ginger. Cut out and discard the core of the cabbage; thinly slice the leaves. Peel the carrots; thinly slice on angle. Cut off and discard the root ends of the scallions; thinly slice, separating the white bottoms and green tops. Cut off and discard the root end of the bok choy; roughly chop. Roughly chop the peanuts.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/WontonNoodle1.png")
ri40 = RecipeItem.create!(recipe_id: r3.id, item_title:"Make the soft-boiled eggs", item_description: "Carefully add the eggs to the pot of boiling water and cook 6 to 7 minutes. Leaving the pot of water boiling, using a slotted spoon or tongs, carefully transfer the cooked eggs to a strainer; rinse under cold water for 30 seconds to 1 minute to stop the cooking process. When cool enough to handle, carefully peel.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/WontonNoodle2.png")
ri41 = RecipeItem.create!(recipe_id: r3.id, item_title:"Cook the vegetables", item_description: "While the eggs cook, in a large, high-sided pan (or pot), heat 1 tablespoon of olive oil on medium-high until hot. Add the chopped ginger and sliced cabbage, carrots, and white bottoms of the scallions. Season with salt and pepper. Cook, stirring frequently, 5 to 6 minutes, or until softened. Add the chopped bok choy and cook, stirring occasionally, 2 to 3 minutes, or until softened. Turn off the heat.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/WontonNoodle3.png")
ri42 = RecipeItem.create!(recipe_id: r3.id, item_title:"Cook the noodles", item_description: "While the vegetables cook, add the noodles to the same pot of boiling water, stirring gently to separate. Cook 2 to 4 minutes, or until tender. Drain thoroughly.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/WontonNoodle4.png")
ri43 = RecipeItem.create!(recipe_id: r3.id, item_title:"Make the sauce", item_description: "While the noodles cook, in a medium bowl, whisk together the soy glaze, tahini, sweet chili sauce, vinegar, and half the soy marinade (you will have extra soy marinade).", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/WontonNoodle5.png")
ri44 = RecipeItem.create!(recipe_id: r3.id, item_title:"Finish and serve", item_description: "Add the cooked noodles and sauce to the pan of cooked vegetables. Cook on medium-high, stirring vigorously, 1 to 2 minutes, or until coated. Turn off the heat. Season with salt and pepper to taste. Serve the finished noodles topped with the soft-boiled eggs. Garnish with the chopped peanuts and sliced green tops of the scallions. Enjoy!", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/WontonNoodle6.png")

ri45 = RecipeItem.create!(recipe_id: r4.id, item_title:"Prepare the ingredients", item_description: "Heat a medium pot of water to boiling on high. Wash and dry the fresh produce. Peel and finely chop the ginger. Cut out and discard the core of the cabbage; thinly slice the leaves. Peel the carrots; thinly slice on angle. Cut off and discard the root ends of the scallions; thinly slice, separating the white bottoms and green tops. Cut off and discard the root end of the bok choy; roughly chop. Roughly chop the peanuts.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/WontonNoodle1.png")
ri46 = RecipeItem.create!(recipe_id: r4.id, item_title:"Make the soft-boiled eggs", item_description: "Carefully add the eggs to the pot of boiling water and cook 6 to 7 minutes. Leaving the pot of water boiling, using a slotted spoon or tongs, carefully transfer the cooked eggs to a strainer; rinse under cold water for 30 seconds to 1 minute to stop the cooking process. When cool enough to handle, carefully peel.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/WontonNoodle2.png")
ri47 = RecipeItem.create!(recipe_id: r4.id, item_title:"Cook the vegetables", item_description: "While the eggs cook, in a large, high-sided pan (or pot), heat 1 tablespoon of olive oil on medium-high until hot. Add the chopped ginger and sliced cabbage, carrots, and white bottoms of the scallions. Season with salt and pepper. Cook, stirring frequently, 5 to 6 minutes, or until softened. Add the chopped bok choy and cook, stirring occasionally, 2 to 3 minutes, or until softened. Turn off the heat.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/WontonNoodle3.png")
ri48 = RecipeItem.create!(recipe_id: r4.id, item_title:"Cook the noodles", item_description: "While the vegetables cook, add the noodles to the same pot of boiling water, stirring gently to separate. Cook 2 to 4 minutes, or until tender. Drain thoroughly.", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/WontonNoodle4.png")
ri49 = RecipeItem.create!(recipe_id: r4.id, item_title:"Make the sauce", item_description: "While the noodles cook, in a medium bowl, whisk together the soy glaze, tahini, sweet chili sauce, vinegar, and half the soy marinade (you will have extra soy marinade).", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/WontonNoodle5.png")
ri50 = RecipeItem.create!(recipe_id: r4.id, item_title:"Finish and serve", item_description: "Add the cooked noodles and sauce to the pan of cooked vegetables. Cook on medium-high, stirring vigorously, 1 to 2 minutes, or until coated. Turn off the heat. Season with salt and pepper to taste. Serve the finished noodles topped with the soft-boiled eggs. Garnish with the chopped peanuts and sliced green tops of the scallions. Enjoy!", item_image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/WontonNoodle6.png")


f1 = Favorite.create!(user_id: u1.id, recipe_id: r1.id);

cr1 = CustomRecipe.create!(user_id: u1.id, title: "Safeway microwavable", description: "It's the best", ingredients: "Want to know how to make lasagna for a casual holiday meal? You can't go wrong with this deliciously rich and meaty lasagna. My grown sons and daughter-in-law request it for their birthdays, too. —Pam Thompson, Girard, Illinois", directions: "Cook noodles according to package directions; drain. Meanwhile, in a Dutch oven, cook sausage, beef and onion over medium heat 8-10 minutes or until meat is no longer pink, breaking up meat into crumbles. Add garlic; cook 1 minute. Drain.
Stir in tomatoes, tomato paste, water, sugar, 3 tablespoons parsley, basil, fennel, 1/2 teaspoon salt and pepper; bring to a boil. Reduce heat; simmer, uncovered, 30 minutes, stirring occasionally.
In a small bowl, mix egg, ricotta cheese, and remaining parsley and salt.
Preheat oven to 375°. Spread 2 cups meat sauce into an ungreased 13x9-in. baking dish. Layer with three noodles and a third of the ricotta mixture. Sprinkle with 1 cup mozzarella cheese and 2 tablespoons Parmesan cheese. Repeat layers twice. Top with remaining meat sauce and cheeses (dish will be full).
Bake, covered, 25 minutes. Bake, uncovered, 25 minutes longer or until bubbly. Let stand 15 minutes before serving. Yield: 12 servings.", image_file_name: "https://s3.us-east-2.amazonaws.com/greenapron/genericfood.png")
# ri3 = RecipeItem.create!(recipe_id: r2.id, item_title: "chicken item", item_description: "asdfaf", item_image_file_name: "asdf")
